# bsd-mailx
# Autogenerated from man page /usr/share/man/man1/bsd-mailx.1.gz
complete -c bsd-mailx -s a -d 'Specify additional header fields on the command line such as "X-Loop: foo@bar…'
complete -c bsd-mailx -s b -d 'Send blind carbon copies to bcc-addr'
complete -c bsd-mailx -s c -d 'Send carbon copies to list of users'
complete -c bsd-mailx -s d -d 'Causes bsd-mailx mail to output all sorts of information useful for debugging…'
complete -c bsd-mailx -s E -d 'Don\'t send messages with an empty body'
complete -c bsd-mailx -s f -d 'Use an alternate mailbox'
complete -c bsd-mailx -s I -d 'Forces bsd-mailx mail to run in interactive mode, even when input is not a te…'
complete -c bsd-mailx -s i -d 'Ignore tty interrupt signals'
complete -c bsd-mailx -s N -d 'Inhibits initial display of message headers when reading mail or editing a ma…'
complete -c bsd-mailx -s n -d 'Inhibits reading /etc/mail. rc upon startup'
complete -c bsd-mailx -s r -d 'Use from-addr as the from address in the message and envelope'
complete -c bsd-mailx -s s -d 'Specify subject on command line (only the first argument after the s flag is …'
complete -c bsd-mailx -s u -d 'Equivalent to: $ mail -f /var/mail/user except that locking is done'
complete -c bsd-mailx -s v -d 'Verbose mode.  The details of delivery are displayed on the user\'s terminal'

