# busybox
# Autogenerated from man page /usr/share/man/man1/busybox.1.gz
complete -c busybox -s o -d '        loop            Ignored (loop devices are autodetected)         [a]sy…'
complete -c busybox -s d -l 'dump		Show'
complete -c busybox -l nnp -l 'no-new-privs	Ignore'
complete -c busybox -l inh-caps
complete -c busybox -l ambient-caps -d 'setsid 4'
complete -c busybox -s K
complete -c busybox -s S

