# cron
# Autogenerated from man page /usr/share/man/man8/cron.8.gz
complete -c cron -s f -d 'Stay in foreground mode, don\\*(Aqt daemonize'
complete -c cron -s l -d 'Enable LSB compliant names for /etc/cron. d files'
complete -c cron -s n -d 'Include the FQDN in the subject when sending mails'
complete -c cron -s N -d 'Run cron jobs Now, immediately, and exit'
complete -c cron -s L
complete -c cron -s x
complete -c cron -l lsbsysinit -d 'option in run-parts'

