# dotlockfile
# Autogenerated from man page /usr/share/man/man1/dotlockfile.1.gz
complete -c dotlockfile -s l -d 'Create a lockfile if no preexisting valid lockfile is found, else wait and re…'
complete -c dotlockfile -s r -d 'The number of times  dotlockfile retries to acquire the lock if it failed the…'
complete -c dotlockfile -s i -d 'Sets a consistent retry interval'
complete -c dotlockfile -s u -d 'Remove a lockfile'
complete -c dotlockfile -s t -d 'Touch an existing lockfile (update the timestamp)'
complete -c dotlockfile -s p -d 'Write the  process-id of the calling process (or dotlockfile itself if a comm…'
complete -c dotlockfile -s m -d 'Lock or unlock the current users mailbox'
complete -c dotlockfile -s q -d 'Don\'t print warnings or errors to the standard error output'
complete -c dotlockfile -s P -d 'On successful "lock and spawn command", don\'t exit with status zero, but pass…'

