# exim_msgdate
# Autogenerated from man page /usr/share/man/man8/exim_msgdate.8.gz
complete -c exim_msgdate -s u -l unix -d 'X Item "-u | --unix" Display time as seconds since 1 Jan 1970, the Unix Epoch'
complete -c exim_msgdate -l GMT -l UTC -s z -l zulu -d 'X Item "--GMT -u|--UTC -z|--zulu" Display time in GMT/UTC - we assume these a…'
complete -c exim_msgdate -s l -l local -d 'X Item "-l | --local" Display time in the local time-zone'
complete -c exim_msgdate -l help -d 'X Item "--help" A brief list of the options'
complete -c exim_msgdate -l man -d 'X Item "--man" A more detailed manual for exim_msgdate'
complete -c exim_msgdate -l debug -d 'X Item "--debug" Information about what went wrong, mostly for developers'
complete -c exim_msgdate -l base -l base36 -l base62 -d 'X Item "--base n | --base36 | --base62" The message-id is usually encoded in …'
complete -c exim_msgdate -l pid -d 'X Item "--pid" Report the process id as well as the date and time in the mess…'
complete -c exim_msgdate -l localhost_number -d 'X Item "--localhost_number n" If the Exim configuration option localhost_numb…'
complete -c exim_msgdate -l C -d 'X Item "--C full path to exim configuration file" This overrides the usual ex…'
complete -c exim_msgdate -o dexim_path

