# exim_id_update
# Autogenerated from man page /usr/share/man/man8/exim_id_update.8.gz
complete -c exim_id_update -s d -d 'Downgrade mode'
complete -c exim_id_update -s h -d 'This help message'
complete -c exim_id_update -s u -d 'Upgrade mode'
complete -c exim_id_update -s v -d Version

