# exim_dbmbuild
# Autogenerated from man page /usr/share/man/man8/exim_dbmbuild.8.gz
complete -c exim_dbmbuild -o nolc -d option
complete -c exim_dbmbuild -o nozero -d 'is given,  exim_dbmbuild creates files without terminating zeroes in either t…'
complete -c exim_dbmbuild -o noduperr -d 'option is used'
complete -c exim_dbmbuild -o lastdup -d 'which causes it to use the data for the last duplicate instead'
complete -c exim_dbmbuild -o nowarn -d 'which stops it listing duplicate keys to “stderr”'

