# exim_lock
# Autogenerated from man page /usr/share/man/man8/exim_lock.8.gz
complete -c exim_lock -o fcntl -d 'Use "fcntl()" locking on the open mailbox'
complete -c exim_lock -o flock -d 'Use "flock()" locking on the open mailbox, provided the operating system supp…'
complete -c exim_lock -o interval -d 'This must be followed by a number, which is a number of seconds; it sets the …'
complete -c exim_lock -o lockfile -d 'Create a lock file before opening the mailbox'
complete -c exim_lock -o mbx -d 'Lock the mailbox using MBX rules'
complete -c exim_lock -s q -d 'Suppress verification output'
complete -c exim_lock -o retries -d 'This must be followed by a number; it sets the number of times to try to get …'
complete -c exim_lock -o restore_time -d 'This option causes exim_lock to restore the modified and read times to the lo…'
complete -c exim_lock -o timeout -d 'This must be followed by a number, which is a number of seconds; it sets a ti…'
complete -c exim_lock -s v -d 'Generate verbose output'

