# exim_checkaccess
# Autogenerated from man page /usr/share/man/man8/exim_checkaccess.8.gz
complete -c exim_checkaccess -o bh -d 'command line argument allows you to run a fake SMTP session with debugging ou…'

