# exiqsumm
# Autogenerated from man page /usr/share/man/man8/exiqsumm.8.gz
complete -c exiqsumm -s a -d and
complete -c exiqsumm -s c -d 'which cause the output to be sorted by oldest message and by count of message…'

