# halt
# Autogenerated from man page /usr/share/man/man8/halt.8.gz
complete -c halt -l help -d 'Print a short help text and exit. sp Added in version 253'
complete -c halt -l halt -d 'Halt the machine, regardless of which one of the three commands is invoked'
complete -c halt -s p -l poweroff -d 'Power off the machine, when either halt or poweroff is invoked'
complete -c halt -l reboot -d 'Reboot the machine, regardless of which one of the three commands is invoked'
complete -c halt -s f -l force -d 'Force immediate power-off, halt, or reboot'
complete -c halt -s w -l wtmp-only -d 'Only write wtmp shutdown entry, do not actually power off, reboot, or halt'
complete -c halt -s d -l no-wtmp -d 'Do not write wtmp shutdown entry. sp Added in version 253'
complete -c halt -s n -l no-sync -d 'Don\\*(Aqt sync hard disks/storage media before power-off, reboot, or halt'
complete -c halt -l no-wall -d 'Do not send wall message before power-off, reboot, or halt'

