# i3-dmenu-desktop
# Autogenerated from man page /usr/share/man/man1/i3-dmenu-desktop.1.gz
complete -c i3-dmenu-desktop -l dmenu -d 'X Item "--dmenu=command" Execute command instead of \'dmenu -i\''
complete -c i3-dmenu-desktop -l entry-type -d 'X Item "--entry-type=type" Display the (localized) "Name" (type = name), the …'
complete -c i3-dmenu-desktop -l show-duplicates

