# i3-save-tree
# Autogenerated from man page /usr/share/man/man1/i3-save-tree.1.gz
complete -c i3-save-tree -l workspace -d 'X Item "--workspace=name|number" Specifies the workspace that should be dumpe…'
complete -c i3-save-tree -l output

