# i3-with-shmlog
# Autogenerated from man page /usr/share/man/man1/i3-with-shmlog.1.gz
complete -c i3-with-shmlog -s a -d 'Disables autostart'
complete -c i3-with-shmlog -s c -d 'Specifies an alternate configuration file path'
complete -c i3-with-shmlog -s C -d 'Check the configuration file for validity and exit'
complete -c i3-with-shmlog -s d -d 'Enables debug logging.  The all parameter is present for historical reasons'
complete -c i3-with-shmlog -s v -d 'Display version number (and date of the last commit)'
complete -c i3-with-shmlog -s V -d 'Be verbose'
complete -c i3-with-shmlog -l force-xinerama -d 'Use Xinerama instead of RandR'
complete -c i3-with-shmlog -l get-socketpath -d 'Retrieve the i3 IPC socket path from X11, print it, then exit'
complete -c i3-with-shmlog -l shmlog-size -d 'Limits the size of the i3 SHM log to <limit> bytes'
complete -c i3-with-shmlog -l replace -d 'Replace an existing window manager'

