# json_xs.1p
# Autogenerated from man page /usr/share/man/man1/json_xs.1p.gz
complete -c 'json_xs.1p' -s v -d 'X Item "-v" Be slightly more verbose'
complete -c 'json_xs.1p' -s f -d 'X Item "-f fromformat" Read a file in the given format from STDIN'
complete -c 'json_xs.1p' -s t -d 'X Item "eval - evaluate the given code as (non-utf-8) Perl, basically the rev…'
complete -c 'json_xs.1p' -s e -d el

