# lsb_release
# Autogenerated from man page /usr/share/man/man1/lsb_release.1.gz
complete -c lsb_release -s h -l help -d 'X Item "-h, --help" Show a help message with a list of options and exit'
complete -c lsb_release -s v -l version -d 'X Item "-v, --version" Show LSB modules this system supports'
complete -c lsb_release -s i -l id -d 'X Item "-i, --id" Show distributor ID'
complete -c lsb_release -s d -l description -d 'X Item "-d, --description" Show description of this distribution'
complete -c lsb_release -s r -l release -d 'X Item "-r, --release" Show release number of this distribution'
complete -c lsb_release -s c -l codename -d 'X Item "-c, --codename" Show code name of this distribution'
complete -c lsb_release -s a -l all -d 'X Item "-a, --all" Show all of the above information'
complete -c lsb_release -s s -l short

