# Mail
# Autogenerated from man page /usr/share/man/man1/Mail.1.gz
complete -c Mail -s a -d 'Specify additional header fields on the command line such as "X-Loop: foo@bar…'
complete -c Mail -s b -d 'Send blind carbon copies to bcc-addr'
complete -c Mail -s c -d 'Send carbon copies to list of users'
complete -c Mail -s d -d 'Causes Mail mail to output all sorts of information useful for debugging Mail…'
complete -c Mail -s E -d 'Don\'t send messages with an empty body'
complete -c Mail -s f -d 'Use an alternate mailbox'
complete -c Mail -s I -d 'Forces Mail mail to run in interactive mode, even when input is not a terminal'
complete -c Mail -s i -d 'Ignore tty interrupt signals'
complete -c Mail -s N -d 'Inhibits initial display of message headers when reading mail or editing a ma…'
complete -c Mail -s n -d 'Inhibits reading /etc/mail. rc upon startup'
complete -c Mail -s r -d 'Use from-addr as the from address in the message and envelope'
complete -c Mail -s s -d 'Specify subject on command line (only the first argument after the s flag is …'
complete -c Mail -s u -d 'Equivalent to: $ mail -f /var/mail/user except that locking is done'
complete -c Mail -s v -d 'Verbose mode.  The details of delivery are displayed on the user\'s terminal'

