# mailtest
# Autogenerated from man page /usr/share/man/man1/mailtest.1.gz
complete -c mailtest -l help -d 'X Item "--help" Print a brief help message and exits'
complete -c mailtest -s d -l debug -d 'X Item "-d, --debug" Enables debugging, outpus additional information whilst …'
complete -c mailtest -s h -l host -d 'X Item "-h, --host=host" Specifies the host to connect to'
complete -c mailtest -s m -l ehlo -d 'X Item "-m, --ehlo=machine" Specified the machine name to use as the EHLO val…'
complete -c mailtest -s r -l rcptto -d 'X Item "-r, --rcptto=recipient" Specifies the recipient of message'
complete -c mailtest -s v -l vrfy -d 'X Item "-v, --vrfy" Uses the recipient parameter for the value in a VRFY requ…'
complete -c mailtest -s e -l expn -d 'X Item "-e, --expn" Uses the recipient parameter for the value in an EXPN req…'
complete -c mailtest -s f -l mailfrom -d 'X Item "-f, --mailfrom=from_address" Specified the value to use in the MAIL F…'
complete -c mailtest -s u -l from822 -d 'X Item "-u, --from822=from_user" Specified the value to use in the message he…'
complete -c mailtest -s B -l bounce -d 'X Item "-B, --bounce" Replace the --mailfrom from_address with <> and the --f…'
complete -c mailtest -s p -l port -d 'X Item "-p, --port=port" Specified the port to connect to on the specified ho…'
complete -c mailtest -s S -l tls -d 'X Item "-S, --tls" Specifies that TLS be used directly on the connection prio…'
complete -c mailtest -s s -l nostarttls -d 'X Item "-s, --nostarttls" Disables attempting STARTTLS if offered'
complete -c mailtest -l stricttls -d 'X Item "--stricttls" Enables strict verification of the TLS connection'
complete -c mailtest -l sslargs -d 'X Item "--sslargs=argname=argvalue[,argname=argvalue'
complete -c mailtest -s b -l body -d 'X Item "-b, --body" Generate a body for the message being sent'
complete -c mailtest -s O -l include-options -d 'X Item "-O, --include-options" Include details of options used in the message…'
complete -c mailtest -s H -l include-headers -d 'X Item "-H, --include-headers" Include a copy of the generated headers in the…'
complete -c mailtest -s w -l wellknown -d 'X Item "-w, --wellknown=well-known-path" Provides the path value for a WELLKN…'
complete -c mailtest -s W -l output

