# nawk
# Autogenerated from man page /usr/share/man/man1/nawk.1.gz
complete -c nawk -s f -d 'Program text is read from file instead of from the command line'
complete -c nawk -s v -d 'assigns  value to program variable R var '
complete -c nawk -s '\\' -d 'indicates the unambiguous end of options'
complete -c nawk -s W -d 'writes an assembler like listing of the internal representation of the progra…'
complete -c nawk -s F -d 'sets the field separator, FS, to value '
complete -c nawk -l version
complete -c nawk -o Wversion
complete -c nawk -l help
complete -c nawk -l posix
complete -c nawk -s r
complete -c nawk -l re-interval
complete -c nawk -l traditional

