# querybts
# Autogenerated from man page /usr/share/man/man1/querybts.1.gz
complete -c querybts -s h -l help -d 'Show summary of options'
complete -c querybts -l version -d 'Show the version of querybts and exit'
complete -c querybts -s A -l archive -d 'Browse archived bugs instead of current reports'
complete -c querybts -s B -l bts -d 'Instead of the Debian bug server, use the server specified by SYSTEM'
complete -c querybts -s b -l buglist -d 'Display a bugs list for the given package'
complete -c querybts -l latest-first -d 'Display the bug reports list sorted and with the latest reports at the top'
complete -c querybts -l mbox-reader-cmd -d 'Specify a command to open the bug reports mbox file'
complete -c querybts -s m -l mbox -d 'Retrieve the given bug number(s) or package name(s) as a mailbox file, instea…'
complete -c querybts -l proxy -l http_proxy -d 'Specify the WWW proxy server to use to handle the queries to the bug tracking…'
complete -c querybts -s s -l source -d 'Query on source packages, rather than binary packages'
complete -c querybts -l timeout -d 'Specify the network timeout, the number of seconds to wait for a resource to …'
complete -c querybts -s u -l ui -l interface -d 'Specify the user interface to use'
complete -c querybts -s w -l web -d 'Launch a web browser to view bug reports, instead of using the internal inter…'

