# systemd-tmpfiles-clean.timer
# Autogenerated from man page /usr/share/man/man8/systemd-tmpfiles-clean.timer.8.gz
complete -c 'systemd-tmpfiles-clean.timer' -l create
complete -c 'systemd-tmpfiles-clean.timer' -l remove
complete -c 'systemd-tmpfiles-clean.timer' -l clean
complete -c 'systemd-tmpfiles-clean.timer' -l replace -d 'is specified, arguments specified on the command line are used instead of the…'
complete -c 'systemd-tmpfiles-clean.timer' -l purge
complete -c 'systemd-tmpfiles-clean.timer' -l dry-run -d '(see below) to verify which files and directories will be deleted'
complete -c 'systemd-tmpfiles-clean.timer' -l user
complete -c 'systemd-tmpfiles-clean.timer' -l boot
complete -c 'systemd-tmpfiles-clean.timer' -l graceful
complete -c 'systemd-tmpfiles-clean.timer' -l prefix
complete -c 'systemd-tmpfiles-clean.timer' -l exclude-prefix
complete -c 'systemd-tmpfiles-clean.timer' -s E
complete -c 'systemd-tmpfiles-clean.timer' -l root
complete -c 'systemd-tmpfiles-clean.timer' -l image
complete -c 'systemd-tmpfiles-clean.timer' -l image-policy
complete -c 'systemd-tmpfiles-clean.timer' -l cat-config
complete -c 'systemd-tmpfiles-clean.timer' -l tldr
complete -c 'systemd-tmpfiles-clean.timer' -l no-pager
complete -c 'systemd-tmpfiles-clean.timer' -s h -l help
complete -c 'systemd-tmpfiles-clean.timer' -l version

