# systemd-tmpfiles-setup.service
# Autogenerated from man page /usr/share/man/man8/systemd-tmpfiles-setup.service.8.gz
complete -c 'systemd-tmpfiles-setup.service' -l create
complete -c 'systemd-tmpfiles-setup.service' -l remove
complete -c 'systemd-tmpfiles-setup.service' -l clean
complete -c 'systemd-tmpfiles-setup.service' -l replace -d 'is specified, arguments specified on the command line are used instead of the…'
complete -c 'systemd-tmpfiles-setup.service' -l purge
complete -c 'systemd-tmpfiles-setup.service' -l dry-run -d '(see below) to verify which files and directories will be deleted'
complete -c 'systemd-tmpfiles-setup.service' -l user
complete -c 'systemd-tmpfiles-setup.service' -l boot
complete -c 'systemd-tmpfiles-setup.service' -l graceful
complete -c 'systemd-tmpfiles-setup.service' -l prefix
complete -c 'systemd-tmpfiles-setup.service' -l exclude-prefix
complete -c 'systemd-tmpfiles-setup.service' -s E
complete -c 'systemd-tmpfiles-setup.service' -l root
complete -c 'systemd-tmpfiles-setup.service' -l image
complete -c 'systemd-tmpfiles-setup.service' -l image-policy
complete -c 'systemd-tmpfiles-setup.service' -l cat-config
complete -c 'systemd-tmpfiles-setup.service' -l tldr
complete -c 'systemd-tmpfiles-setup.service' -l no-pager
complete -c 'systemd-tmpfiles-setup.service' -s h -l help
complete -c 'systemd-tmpfiles-setup.service' -l version

