# tasksel
# Autogenerated from man page /usr/share/man/man8/tasksel.8.gz
complete -c tasksel -s t -l test -d 'X Item "-t, --test" test mode; don\'t actually install or remove packages'
complete -c tasksel -l new-install -d 'X Item "--new-install" automatically select some tasks without even displayin…'
complete -c tasksel -l list-tasks -d 'X Item "--list-tasks" list on stdout the tasks that would be displayed in the…'
complete -c tasksel -l task-packages -d 'X Item "--task-packages task" lists on stdout the packages that are available…'
complete -c tasksel -l task-desc -d 'X Item "--task-desc task" outputs the extended description of the given task'
complete -c tasksel -l debconf-apt-progress

