# telnet
# Autogenerated from man page /usr/share/man/man1/telnet.1.gz
complete -c telnet -s 4 -d 'Use IPv4 to connect to hosts'
complete -c telnet -s 6 -d 'Use IPv6 to connect to hosts'
complete -c telnet -s 8 -d 'Specifies an 8-bit data path'
complete -c telnet -s L -d 'Specifies an 8-bit data path on output'
complete -c telnet -s e -d 'Sets the initial telnet telnet escape character to escape-char'
complete -c telnet -s E -d 'Stops any character from being recognized as an escape character'
complete -c telnet -s a -d 'Attempt automatic login'
complete -c telnet -s K -d 'Specifies no automatic login to the remote system'
complete -c telnet -s l -d 'When connecting to the remote system, if the remote system understands the EN…'
complete -c telnet -s n -d 'Opens tracefile for recording trace information'
complete -c telnet -s r -d 'Specifies a user interface similar to rlogin 1'
complete -c telnet -s c -d 'Disables the reading of the user\'s \\&. telnetrc file'
complete -c telnet -s d -d 'Sets the initial value of the debug toggle to TRUE'
complete -c telnet -s x -d 'Turns on encryption of the data stream if possible'
complete -c telnet -s X -d 'Disables the atype type of authentication'
complete -c telnet -s k -d 'If Kerberos authentication is being used, the k option requests that telnet o…'

