# tryaffix
# Autogenerated from man page /usr/share/man/man1/tryaffix.1.gz
complete -c tryaffix -s M -d 'switch is specified, a one-line mini-menu at the bottom of the screen will su…'
complete -c tryaffix -s N -d 'switch may be used to suppress the mini-menu'
complete -c tryaffix -s L -d 'flag is given, the specified number is used as the number of lines of context…'
complete -c tryaffix -s V -d 'flag is given, characters that are not in the 7-bit ANSI printable character …'
complete -c tryaffix -s l
complete -c tryaffix -s a -d and
complete -c tryaffix -s A -d 'options and interactive mode (see below) also accepts the following "common" …'
complete -c tryaffix -s t -d 'The input file is in TeX or LaTeX format'
complete -c tryaffix -s n -d 'The input file is in nroff/troff format'
complete -c tryaffix -s H -d 'The input file is in SGML/HTML format.  (This should really be'
complete -c tryaffix -s s -d 'but for historical reasons that flag was already taken. )'
complete -c tryaffix -s o -d 'The input file should be treated as ordinary text'
complete -c tryaffix -s g -d 'The input file is in Debian control file format'
complete -c tryaffix -s b -d 'Create a backup file by appending ". bak" to the name of the input file'
complete -c tryaffix -s x -d 'Delete the backup file after spell-checking is finished'
complete -c tryaffix -s B -d 'Report run-together words with missing blanks as spelling errors'
complete -c tryaffix -s C -d 'Consider run-together words as valid compounds'
complete -c tryaffix -s P -d 'Don\'t generate extra root/affix combinations'
complete -c tryaffix -s m -d 'Make possible root/affix combinations that aren\'t in the dictionary'
complete -c tryaffix -s S -d 'Sort the list of guesses by probable correctness'
complete -c tryaffix -s d -d 'Specify an alternate dictionary file.  For example, use'
complete -c tryaffix -s p -d 'Specify an alternate personal dictionary'
complete -c tryaffix -s w -d 'Specify additional characters that can be part of a word'
complete -c tryaffix -s W -d 'Specify length of words that are always valid'
complete -c tryaffix -s T -d 'Assume a given formatter type for all files.  The'
complete -c tryaffix -s k -d 'option is used to enhance the behavior of certain deformatters'
complete -c tryaffix -o ktexskip1 -d 'adds "bibliographystyle" to the TeX skip-1 list, while'
complete -c tryaffix -o khtmlignore -d 'replaces the HTML ignore list with "pre" and "strong"'
complete -c tryaffix -s F -d 'switch specifies an external deformatter program'
complete -c tryaffix -s f -d 'option is only valid in conjunction with the'
complete -c tryaffix -s v -d 'option causes ispell to print its current version identification on the stand…'
complete -c tryaffix -s c
complete -c tryaffix -s e -d and
complete -c tryaffix -s D -d 'options of ispell , are primarily intended for use by the munchlist shell scr…'
complete -c tryaffix -o 'strip+add<tab>count<tab>bytes'
complete -c tryaffix -s u -d 'switch specifies that sort (1) uses unsigned comparisons'

