# update-exim4.conf.template
# Autogenerated from man page /usr/share/man/man8/update-exim4.conf.template.8.gz
complete -c 'update-exim4.conf.template' -s h -l help -d 'Show short help message and exit'
complete -c 'update-exim4.conf.template' -s n -l nobackup -d 'Overwrite existing file, instead of keeping it as /etc/exim4/exim4. conf'
complete -c 'update-exim4.conf.template' -s o -l output -d 'Write output to file instead of /etc/exim4/exim4. conf. template'
complete -c 'update-exim4.conf.template' -s r -l run -d 'Actually do something.  If this option is not specified update-exim4. conf'

