# update-exim4.conf
# Autogenerated from man page /usr/share/man/man8/update-exim4.conf.8.gz
complete -c 'update-exim4.conf' -l check -d 'Generate temporary configuration file, check its validity and exit with eithe…'
complete -c 'update-exim4.conf' -s d -l confdir -d 'Read input from directory instead of /etc/exim4'
complete -c 'update-exim4.conf' -s h -l help -d 'Show short help message and exit'
complete -c 'update-exim4.conf' -l keepcomments -d 'Do not remove comment lines from the output file'
complete -c 'update-exim4.conf' -s o -l output -d 'Write output to file instead of /var/lib/exim4/config. autogenerated'
complete -c 'update-exim4.conf' -l removecomments -d 'Remove comment lines from the output file.  [Default]'
complete -c 'update-exim4.conf' -s v -l verbose -d 'Enable verbose mode'

