# wcurl
# Autogenerated from man page /usr/share/man/man1/wcurl.1.gz
complete -c wcurl -l curl-options -l curl-options -d 'Specify extra options to be passed when invoking curl'
complete -c wcurl -l dry-run -d 'Don\'t actually execute curl, just print what would be invoked'
complete -c wcurl -s V -l version -d 'Print version information'
complete -c wcurl -s h -l help -d 'Print help message'

