# x-terminal-emulator
# Autogenerated from man page /usr/share/man/man1/x-terminal-emulator.1.gz
complete -c x-terminal-emulator -s e -l command -d PP
complete -c x-terminal-emulator -l config-file -d PP
complete -c x-terminal-emulator -s o -l option -d PP
complete -c x-terminal-emulator -l socket -d PP
complete -c x-terminal-emulator -s T -l title -d PP

