# x-window-manager
# Autogenerated from man page /usr/share/man/man1/x-window-manager.1.gz
complete -c x-window-manager -s a -d 'Disables autostart'
complete -c x-window-manager -s c -d 'Specifies an alternate configuration file path'
complete -c x-window-manager -s C -d 'Check the configuration file for validity and exit'
complete -c x-window-manager -s d -d 'Enables debug logging.  The all parameter is present for historical reasons'
complete -c x-window-manager -s v -d 'Display version number (and date of the last commit)'
complete -c x-window-manager -s V -d 'Be verbose'
complete -c x-window-manager -l force-xinerama -d 'Use Xinerama instead of RandR'
complete -c x-window-manager -l get-socketpath -d 'Retrieve the i3 IPC socket path from X11, print it, then exit'
complete -c x-window-manager -l shmlog-size -d 'Limits the size of the i3 SHM log to <limit> bytes'
complete -c x-window-manager -l replace -d 'Replace an existing window manager'

