# x-www-browser
# Autogenerated from man page /usr/share/man/man1/x-www-browser.1.gz
complete -c x-www-browser -l display -d 'X display to use'
complete -c x-www-browser -l sync -d 'Make X calls synchronous'
complete -c x-www-browser -l no-xshm -d 'Don\'t use X shared memory extension'
complete -c x-www-browser -l g-fatal-warnings -d 'Make all warnings fatal  . SS "Mozilla options"'
complete -c x-www-browser -s h -o help -d 'Show summary of options'
complete -c x-www-browser -s v -o version -d 'Print Firefox ESR version'
complete -c x-www-browser -s P -d 'Start with profile.  When no profile is given, displays the Profile Manager'
complete -c x-www-browser -o migration -d 'Start with migration wizard.  May require -no-remote, see below'
complete -c x-www-browser -o ProfileManager -d 'Start with profile manager.  May require -no-remote, see below'
complete -c x-www-browser -o no-remote -d 'Don\'t connect to a running Firefox ESR instance'
complete -c x-www-browser -o UILocale -d 'Start with locale resources as User Interface locale'
complete -c x-www-browser -o safe-mode -d 'Starts Firefox ESR in safe mode, i. e'
complete -c x-www-browser -o jsconsole -d 'Start with Javascript Console'
complete -c x-www-browser -o new-window -d 'Open URL in a new window in an already running Firefox ESR process'
complete -c x-www-browser -o new-tab -d 'Open URL in a new tab in an already running Firefox ESR process'
complete -c x-www-browser -l xim-preedit
complete -c x-www-browser -l xim-status
complete -c x-www-browser -o chrome -d 'Load the specified chrome'

